name: exp
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.8.0 # upgraded from 1.7.2 for ClassicalMDS
  # - statsmodels
  # - xgboost
  - pandas=2.3.3
  - matplotlib=3.10.7
  - networkx=3.5
  - joblib=1.5.2
  - tqdm=4.67.1
  - ipykernel
  - ipympl
  - plotly=5.24.1
  - nbformat
  - dash=3.2.0
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - mlflow=3.2.0
  - optuna=4.5.0
  - pymoo=0.6.1.5
  - pip
  - deap=1.4.3
  - pip:
      # - dash-ag-grid
      # - dash-tabulator
      - pgmpy
      - paramiko
      - python-dotenv
      - httpx
      - email_validator
      - python-multipart
      - websockets
      - websocket-client
      - PySocks
      - watchfiles
      - prometheus_flask_exporter
      - grpcio-status
      - h2
      - httptools